apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  maxReplicas: 7
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydata
  metrics:
  - type:  Resource
    resource:
      name: memory
      targetAverageUtilization: 40
  - type: Resource
    resource:
       name: cpu
       targetAverageUtilization: 30
